In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

In [ ]:
## Data import
repress = pd.read_table("/content/drive/My Drive/생물정보학 실습/3. Random forest/sorted.repressedEnhancer.EZH2.both0.50.intersect.wMergedHistones.gencode.v34lift37.annotation.bed",header=None)
active1 = pd.read_table("/content/drive/My Drive/생물정보학 실습/3. Random forest/sorted.activeEnhancer.EP300_1.both0.50.intersect.wMergedHistones.gencode.v34lift37.annotation.bed",header=None)
active2 = pd.read_table("/content/drive/My Drive/생물정보학 실습/3. Random forest/sorted.activeEnhancer.EP300_2.both0.50.intersect.wMergedHistones.gencode.v34lift37.annotation.bed",header=None)

In [2]:
repress = pd.read_table("sorted.repressedEnhancer.EZH2.both0.50.intersect.wMergedHistones.gencode.v34lift37.annotation.bed",header=None)
active1 = pd.read_table("sorted.activeEnhancer.EP300_1.both0.50.intersect.wMergedHistones.gencode.v34lift37.annotation.bed",header=None)
active2 = pd.read_table("sorted.activeEnhancer.EP300_2.both0.50.intersect.wMergedHistones.gencode.v34lift37.annotation.bed",header=None)

In [5]:
## concatenate active1 and active2
active = pd.concat((active1,active2))

In [6]:
active

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,chr1,1217050,1217426,.,866,.,26.36167,-1.0,0.97528,188,...,170,chr1,1215816,1227409,ENSG00000162572.21_5,SCNN1D,protein_coding,HAVANA,full_contig,0
1,chr1,3585407,3585783,.,650,.,24.96101,-1.0,0.96919,188,...,114,chr1,3569080,3652765,ENSG00000078900.15_8,TP73,protein_coding,HAVANA,full_contig,0
2,chr1,6264932,6265308,.,676,.,23.20480,-1.0,0.94664,188,...,244,chr1,6245080,6269449,ENSG00000116251.11_7,RPL22,protein_coding,HAVANA,full_contig,0
3,chr1,6264932,6265308,.,676,.,23.20480,-1.0,0.94664,188,...,244,chr1,6264900,6265840,ENSG00000226944.1_8,AL031847.1,lncRNA,HAVANA,full_contig,0
4,chr1,6264932,6265308,.,676,.,23.20480,-1.0,0.94664,188,...,183,chr1,6245080,6269449,ENSG00000116251.11_7,RPL22,protein_coding,HAVANA,full_contig,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8161,chrX,153276008,153276332,.,562,.,5.82131,-1.0,-0.01110,162,...,67,chrX,153275957,153285353,ENSG00000184216.14_10,IRAK1,protein_coding,HAVANA,full_contig,0
8162,chrX,153305894,153306218,.,620,.,19.21680,-1.0,2.16978,162,...,129,chrX,153287024,153402578,ENSG00000169057.23_9,MECP2,protein_coding,HAVANA,partial,0
8163,chrX,153587219,153587543,.,554,.,20.32860,-1.0,2.34613,162,...,76,chrX,153576892,153603006,ENSG00000196924.18_8,FLNA,protein_coding,HAVANA,full_contig,0
8164,chrX,153587219,153587543,.,554,.,20.32860,-1.0,2.34613,162,...,114,chrX,153576892,153603006,ENSG00000196924.18_8,FLNA,protein_coding,HAVANA,full_contig,0
8165,chrY,16740106,16740430,.,1000,.,79.45473,-1.0,4.64539,162,...,117,chrY,16634453,16957530,ENSG00000165246.14_8,NLGN4Y,protein_coding,HAVANA,full_contig,0

In [7]:
repress.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,chr1,855129,855773,.,774,.,36.28270,-1.0,4.06292,322,...,203,chr1,852245,856396,ENSG00000223764.2_8,LINC02593,lncRNA,HAVANA,full_contig,0
1,chr1,858889,859234,.,789,.,37.76190,-1.0,4.06292,154,...,297,chr1,859308,879961,ENSG00000187634.12_9,SAMD11,protein_coding,HAVANA,full_contig,75
2,chr1,860975,861967,.,1000,.,43.99065,-1.0,4.06292,678,...,599,chr1,859308,879961,ENSG00000187634.12_9,SAMD11,protein_coding,HAVANA,full_contig,0
3,chr1,860975,861967,.,1000,.,43.99065,-1.0,4.06292,678,...,268,chr1,859308,879961,ENSG00000187634.12_9,SAMD11,protein_coding,HAVANA,full_contig,0
4,chr1,860975,861967,.,1000,.,99.08340,-1.0,4.06292,477,...,599,chr1,859308,879961,ENSG00000187634.12_9,SAMD11,protein_coding,HAVANA,full_contig,0

## column 정보

### represssor or active info
    "chrom","chromStart","chromEnd","string name","score","strand","signalValue","pValue","qValue","peak",  
### Histone info
    "Histone","Histone chrom","HchromStart","HchromEnd","Hstring name","Hscore","Hstrand","HsignalValue","HpValue","HqValue","Hpeak",
### genecode info
    "seqname", "start","end","gene_id","gene_name","gene_type","source","remap_status","distance with gene"

In [ ]:
## 필요한 정보 : "Histone", "HsignalValue", "seqname", "start","end", "gene_name", "distance with gene"

In [8]:
## repressive enhancer
ezh2 = repress.loc[:,[10,17,21,22,23,25,29]]
ezh2.columns = ["Histone", "HsignalValue", "chr","start","end","gene_name", "distance with gene"]
ezh2

,Histone,HsignalValue,chr,start,end,gene_name,distance with gene
0,H3K27me3_2.bed,5.36218,chr1,852245,856396,LINC02593,0
1,H3K4me3_1.bed,7.76733,chr1,859308,879961,SAMD11,75
2,H3K27me3_1.bed,6.83947,chr1,859308,879961,SAMD11,0
3,H3K27me3_2.bed,7.76273,chr1,859308,879961,SAMD11,0
4,H3K27me3_1.bed,6.83947,chr1,859308,879961,SAMD11,0
...,...,...,...,...,...,...,...
9036,H3K27me3_1.bed,3.63738,chrX,153067621,153096020,PDZD4,720
9037,H3K27me3_1.bed,7.63849,chrX,153903526,153979858,GAB3,0
9038,H3K4me1.bed,3.45406,chrX,153903526,153979858,GAB3,0
9039,H3K4me2.bed,8.02465,chrX,153903526,153979858,GAB3,0
9040,H3K4me2.bed,8.02465,chrX,153903526,153979858,GAB3,0

In [9]:
## active enhancer
ep300 = active.loc[:,[10,17,21,22,23,25,29]]
ep300.columns =  ["Histone", "HsignalValue", "chr","start","end","gene_name", "distance with gene"]

In [10]:
ep300

,Histone,HsignalValue,chr,start,end,gene_name,distance with gene
0,H3K4me3_2.bed,3.81197,chr1,1215816,1227409,SCNN1D,0
1,H3K4me3_1.bed,7.62992,chr1,3569080,3652765,TP73,0
2,H3K4me1.bed,5.51486,chr1,6245080,6269449,RPL22,0
3,H3K4me1.bed,5.51486,chr1,6264900,6265840,AL031847.1,0
4,H3K4me3_2.bed,7.04172,chr1,6245080,6269449,RPL22,0
...,...,...,...,...,...,...,...
8161,H3K9ac.bed,4.33856,chrX,153275957,153285353,IRAK1,0
8162,H3K79me2.bed,4.90406,chrX,153287024,153402578,MECP2,0
8163,H3K36me3.bed,4.41572,chrX,153576892,153603006,FLNA,0
8164,H3K4me2.bed,3.32335,chrX,153576892,153603006,FLNA,0
8165,H3K4me2.bed,5.18598,chrY,16634453,16957530,NLGN4Y,0

In [16]:
# chrom + chromStart + chromEnd -> Pos (chr:####-####)
# Histone.bed -> Histone
# 동일한 gene에서 같은 종류의 histone이 발견되면 distance가 적은 걸로, distance가 같으면 HsignalValue가 큰 값을 남기기

def reshape_df(df):
    df['Pos'] = 'tmp'
    
    for idx in range(len(df)):
        df['Pos'][idx] = f'{df["chr"][idx]}:{df["start"][idx]}-{df["end"][idx]}'
        df['Histone'][idx] = df['Histone'][idx].split('.')[0].split('_')[0]
    
    result = df.reindex(columns = ['Pos', 'gene_name', 'distance with gene',
                                  'Histone', 'HsignalValue'])
    return result

In [14]:
ep300 = ep300.reset_index(drop=True)
ep300

,Histone,HsignalValue,chr,start,end,gene_name,distance with gene
0,H3K4me3_2.bed,3.81197,chr1,1215816,1227409,SCNN1D,0
1,H3K4me3_1.bed,7.62992,chr1,3569080,3652765,TP73,0
2,H3K4me1.bed,5.51486,chr1,6245080,6269449,RPL22,0
3,H3K4me1.bed,5.51486,chr1,6264900,6265840,AL031847.1,0
4,H3K4me3_2.bed,7.04172,chr1,6245080,6269449,RPL22,0
...,...,...,...,...,...,...,...
10336,H3K9ac.bed,4.33856,chrX,153275957,153285353,IRAK1,0
10337,H3K79me2.bed,4.90406,chrX,153287024,153402578,MECP2,0
10338,H3K36me3.bed,4.41572,chrX,153576892,153603006,FLNA,0
10339,H3K4me2.bed,3.32335,chrX,153576892,153603006,FLNA,0
10340,H3K4me2.bed,5.18598,chrY,16634453,16957530,NLGN4Y,0

In [17]:
EZH2 = reshape_df(ezh2)
EP300 = reshape_df(ep300)

/var/folders/jt/gs5p05p51q57t329kqk72q3h0000gn/T/ipykernel_32107/4121016914.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pos'][idx] = f'{df["chr"][idx]}:{df["start"][idx]}-{df["end"][idx]}'
/var/folders/jt/gs5p05p51q57t329kqk72q3h0000gn/T/ipykernel_32107/4121016914.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Histone'][idx] = df['Histone'][idx].split('.')[0].split('_')[0]

In [20]:
EZH2['enhancer'] = 'EZH2'
EZH2

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer
0,chr1:852245-856396,LINC02593,0,H3K27me3,5.36218,EZH2
1,chr1:859308-879961,SAMD11,75,H3K4me3,7.76733,EZH2
2,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
3,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
4,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
...,...,...,...,...,...,...
9036,chrX:153067621-153096020,PDZD4,720,H3K27me3,3.63738,EZH2
9037,chrX:153903526-153979858,GAB3,0,H3K27me3,7.63849,EZH2
9038,chrX:153903526-153979858,GAB3,0,H3K4me1,3.45406,EZH2
9039,chrX:153903526-153979858,GAB3,0,H3K4me2,8.02465,EZH2
9040,chrX:153903526-153979858,GAB3,0,H3K4me2,8.02465,EZH2

In [21]:
EP300['enhancer'] = 'EP300'
EP300

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer
0,chr1:1215816-1227409,SCNN1D,0,H3K4me3,3.81197,EP300
1,chr1:3569080-3652765,TP73,0,H3K4me3,7.62992,EP300
2,chr1:6245080-6269449,RPL22,0,H3K4me1,5.51486,EP300
3,chr1:6264900-6265840,AL031847.1,0,H3K4me1,5.51486,EP300
4,chr1:6245080-6269449,RPL22,0,H3K4me3,7.04172,EP300
...,...,...,...,...,...,...
10336,chrX:153275957-153285353,IRAK1,0,H3K9ac,4.33856,EP300
10337,chrX:153287024-153402578,MECP2,0,H3K79me2,4.90406,EP300
10338,chrX:153576892-153603006,FLNA,0,H3K36me3,4.41572,EP300
10339,chrX:153576892-153603006,FLNA,0,H3K4me2,3.32335,EP300
10340,chrY:16634453-16957530,NLGN4Y,0,H3K4me2,5.18598,EP300

In [22]:
concatDF = pd.concat([EZH2, EP300])
concatDF

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer
0,chr1:852245-856396,LINC02593,0,H3K27me3,5.36218,EZH2
1,chr1:859308-879961,SAMD11,75,H3K4me3,7.76733,EZH2
2,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
3,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
4,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
...,...,...,...,...,...,...
10336,chrX:153275957-153285353,IRAK1,0,H3K9ac,4.33856,EP300
10337,chrX:153287024-153402578,MECP2,0,H3K79me2,4.90406,EP300
10338,chrX:153576892-153603006,FLNA,0,H3K36me3,4.41572,EP300
10339,chrX:153576892-153603006,FLNA,0,H3K4me2,3.32335,EP300
10340,chrY:16634453-16957530,NLGN4Y,0,H3K4me2,5.18598,EP300

In [23]:
concatDF = concatDF.reset_index(drop=True)
concatDF

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer
0,chr1:852245-856396,LINC02593,0,H3K27me3,5.36218,EZH2
1,chr1:859308-879961,SAMD11,75,H3K4me3,7.76733,EZH2
2,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
3,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
4,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
...,...,...,...,...,...,...
19377,chrX:153275957-153285353,IRAK1,0,H3K9ac,4.33856,EP300
19378,chrX:153287024-153402578,MECP2,0,H3K79me2,4.90406,EP300
19379,chrX:153576892-153603006,FLNA,0,H3K36me3,4.41572,EP300
19380,chrX:153576892-153603006,FLNA,0,H3K4me2,3.32335,EP300
19381,chrY:16634453-16957530,NLGN4Y,0,H3K4me2,5.18598,EP300

In [24]:
concatDF[concatDF['gene_name']=='SAMD11']

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer
1,chr1:859308-879961,SAMD11,75,H3K4me3,7.76733,EZH2
2,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
3,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
4,chr1:859308-879961,SAMD11,0,H3K27me3,6.83947,EZH2
5,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
6,chr1:859308-879961,SAMD11,0,H3K27me3,8.16884,EZH2
7,chr1:859308-879961,SAMD11,0,H3K27me3,5.45606,EZH2
8,chr1:859308-879961,SAMD11,0,H3K4me1,3.66994,EZH2
9,chr1:859308-879961,SAMD11,0,H3K27me3,4.37253,EZH2
10,chr1:859308-879961,SAMD11,0,H3K27me3,4.41334,EZH2
11,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
12,chr1:859308-879961,SAMD11,0,H3K4me1,4.61581,EZH2
13,chr1:859308-879961,SAMD11,0,H3K27me3,7.76273,EZH2
14,chr1:859308-879961,SAMD11,0,H3K4me1,4.61581,EZH2
15,chr1:859308-879961,SAMD11,0,H3K4me3,4.00192,EZH2
16,chr1:859308-879961,SAMD11,0,H3K4me3,6.83775,EZH2

In [26]:
len(concatDF['gene_name'].unique())

7385

In [30]:
from tqdm.notebook import tqdm

In [31]:
## 동일한 유전자에서 같은 histone이 발견되면 distance 적은 걸로, 같으면 HsignalValue가 큰 값을 남기기. 
## 같으면 둘중 하나 없애
## list에 넣어서 drop(list)

rm_list = []
for gene in tqdm(concatDF['gene_name'].unique()):
    tmp_df = concatDF[concatDF['gene_name']==gene]
    for idx in list(tmp_df.index):
        for i in list(tmp_df.index):
            if (idx < i) & (tmp_df.loc[idx, "Histone"]==tmp_df.loc[i, "Histone"]) & (tmp_df.loc[idx,'enhancer']==tmp_df.loc[i,'enhancer']):
                if tmp_df.loc[idx, 'distance with gene'] < tmp_df.loc[i,'distance with gene']:
                    rm_list.append(i)
                elif tmp_df.loc[idx, 'distance with gene'] > tmp_df.loc[i,'distance with gene']:
                    rm_list.append(idx)
                elif tmp_df.loc[idx, 'distance with gene'] == tmp_df.loc[i,'distance with gene']:
                    if tmp_df.loc[idx, 'HsignalValue'] < tmp_df.loc[i, 'HsignalValue']:
                        rm_list.append(idx)
                    elif tmp_df.loc[idx, 'HsignalValue'] >= tmp_df.loc[i, 'HsignalValue']:
                        rm_list.append(i)
                        
rm_list = list(set(rm_list))
len(rm_list)

  0%|          | 0/7385 [00:00<?, ?it/s]

6498

In [33]:
concatDF = concatDF.drop(rm_list)

In [35]:
concatDF = concatDF.reset_index(drop=True)
concatDF

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer
0,chr1:852245-856396,LINC02593,0,H3K27me3,5.36218,EZH2
1,chr1:859308-879961,SAMD11,0,H3K27me3,8.16884,EZH2
2,chr1:859308-879961,SAMD11,0,H3K4me1,4.61581,EZH2
3,chr1:859308-879961,SAMD11,0,H3K4me3,6.83775,EZH2
4,chr1:910584-917473,PERM1,0,H3K4me1,4.53346,EZH2
...,...,...,...,...,...,...
12879,chrX:153275957-153285353,IRAK1,0,H3K9ac,4.33856,EP300
12880,chrX:153287024-153402578,MECP2,0,H3K79me2,4.90406,EP300
12881,chrX:153576892-153603006,FLNA,0,H3K36me3,4.41572,EP300
12882,chrX:153576892-153603006,FLNA,0,H3K4me2,3.32335,EP300
12883,chrY:16634453-16957530,NLGN4Y,0,H3K4me2,5.18598,EP300

In [37]:
# reshape dataframe

pivotDF1 = pd.pivot_table(data=concatDF, 
                          index = ['Pos', 'gene_name'],  
                          columns=['Histone'],
                          fill_value=0,
                          values = 'HsignalValue')
pivotDF1

,Histone,H3K27me3,H3K36me3,H3K4me1,H3K4me2,H3K4me3,H3K79me2,H3K9ac,H3K9me3,H4K20me1
Pos,gene_name,,,,,,,,,
chr10:100216834-100995619,HPSE2,0.00000,0.0,0.0,5.81644,0.00000,0.0,0.0,0.0,0.0
chr10:101156627-101190381,GOT1,0.00000,0.0,0.0,3.98603,0.00000,0.0,0.0,0.0,0.0
chr10:101286107-101290934,LINC01475,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0
chr10:101286705-101288224,AL513542.1,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0
chr10:101292699-101296281,NKX2-3,8.02894,0.0,0.0,13.50215,9.78393,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
chrX:9217960-9243246,AC003684.1,0.00000,0.0,0.0,4.01233,0.00000,0.0,0.0,0.0,0.0
chrX:9983294-10112514,WWC3,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0
chrX:99899192-99930785,SRPX2,0.00000,0.0,0.0,0.00000,4.75055,0.0,0.0,0.0,0.0
chrX:9992882-10006694,WWC3-AS1,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0
chrY:16634453-16957530,NLGN4Y,0.00000,0.0,0.0,5.18598,0.00000,0.0,0.0,0.0,0.0

In [38]:
concatDF['value'] = 1

In [39]:
concatDF

,Pos,gene_name,distance with gene,Histone,HsignalValue,enhancer,value
0,chr1:852245-856396,LINC02593,0,H3K27me3,5.36218,EZH2,1
1,chr1:859308-879961,SAMD11,0,H3K27me3,8.16884,EZH2,1
2,chr1:859308-879961,SAMD11,0,H3K4me1,4.61581,EZH2,1
3,chr1:859308-879961,SAMD11,0,H3K4me3,6.83775,EZH2,1
4,chr1:910584-917473,PERM1,0,H3K4me1,4.53346,EZH2,1
...,...,...,...,...,...,...,...
12879,chrX:153275957-153285353,IRAK1,0,H3K9ac,4.33856,EP300,1
12880,chrX:153287024-153402578,MECP2,0,H3K79me2,4.90406,EP300,1
12881,chrX:153576892-153603006,FLNA,0,H3K36me3,4.41572,EP300,1
12882,chrX:153576892-153603006,FLNA,0,H3K4me2,3.32335,EP300,1
12883,chrY:16634453-16957530,NLGN4Y,0,H3K4me2,5.18598,EP300,1

In [41]:
pivotDF2 = pd.pivot_table(data=concatDF, 
                          index=['Pos', 'gene_name'], 
                          columns="enhancer",
                         fill_value=0,
                         values='value')
pivotDF2

enhancer                              EP300  EZH2
Pos                       gene_name
chr10:100216834-100995619 HPSE2           1     0
chr10:101156627-101190381 GOT1            1     0
chr10:101286107-101290934 LINC01475       0     1
chr10:101286705-101288224 AL513542.1      0     1
chr10:101292699-101296281 NKX2-3          0     1
...                                     ...   ...
chrX:9217960-9243246      AC003684.1      1     0
chrX:9983294-10112514     WWC3            1     0
chrX:99899192-99930785    SRPX2           1     0
chrX:9992882-10006694     WWC3-AS1        1     0
chrY:16634453-16957530    NLGN4Y          1     0

[7402 rows x 2 columns]

In [42]:
mergedDF = pivotDF1.merge(pivotDF2, left_index=True, right_index=True)
mergedDF

,,H3K27me3,H3K36me3,H3K4me1,H3K4me2,H3K4me3,H3K79me2,H3K9ac,H3K9me3,H4K20me1,EP300,EZH2
Pos,gene_name,,,,,,,,,,,
chr10:100216834-100995619,HPSE2,0.00000,0.0,0.0,5.81644,0.00000,0.0,0.0,0.0,0.0,1,0
chr10:101156627-101190381,GOT1,0.00000,0.0,0.0,3.98603,0.00000,0.0,0.0,0.0,0.0,1,0
chr10:101286107-101290934,LINC01475,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0,1
chr10:101286705-101288224,AL513542.1,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0,1
chr10:101292699-101296281,NKX2-3,8.02894,0.0,0.0,13.50215,9.78393,0.0,0.0,0.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
chrX:9217960-9243246,AC003684.1,0.00000,0.0,0.0,4.01233,0.00000,0.0,0.0,0.0,0.0,1,0
chrX:9983294-10112514,WWC3,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1,0
chrX:99899192-99930785,SRPX2,0.00000,0.0,0.0,0.00000,4.75055,0.0,0.0,0.0,0.0,1,0
chrX:9992882-10006694,WWC3-AS1,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1,0
chrY:16634453-16957530,NLGN4Y,0.00000,0.0,0.0,5.18598,0.00000,0.0,0.0,0.0,0.0,1,0

In [45]:
## EP300과 EZH2 가 둘다 1이거나 둘다 0인 데이터 삭제

mergedDF = mergedDF[mergedDF['EP300']!=mergedDF['EZH2']]
mergedDF

,,H3K27me3,H3K36me3,H3K4me1,H3K4me2,H3K4me3,H3K79me2,H3K9ac,H3K9me3,H4K20me1,EP300,EZH2
Pos,gene_name,,,,,,,,,,,
chr10:100216834-100995619,HPSE2,0.00000,0.0,0.0,5.81644,0.00000,0.0,0.0,0.0,0.0,1,0
chr10:101156627-101190381,GOT1,0.00000,0.0,0.0,3.98603,0.00000,0.0,0.0,0.0,0.0,1,0
chr10:101286107-101290934,LINC01475,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0,1
chr10:101286705-101288224,AL513542.1,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0,1
chr10:101292699-101296281,NKX2-3,8.02894,0.0,0.0,13.50215,9.78393,0.0,0.0,0.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
chrX:9217960-9243246,AC003684.1,0.00000,0.0,0.0,4.01233,0.00000,0.0,0.0,0.0,0.0,1,0
chrX:9983294-10112514,WWC3,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1,0
chrX:99899192-99930785,SRPX2,0.00000,0.0,0.0,0.00000,4.75055,0.0,0.0,0.0,0.0,1,0
chrX:9992882-10006694,WWC3-AS1,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1,0
chrY:16634453-16957530,NLGN4Y,0.00000,0.0,0.0,5.18598,0.00000,0.0,0.0,0.0,0.0,1,0

In [47]:
finalDF = mergedDF.iloc[:,:-1]
finalDF

,,H3K27me3,H3K36me3,H3K4me1,H3K4me2,H3K4me3,H3K79me2,H3K9ac,H3K9me3,H4K20me1,EP300
Pos,gene_name,,,,,,,,,,
chr10:100216834-100995619,HPSE2,0.00000,0.0,0.0,5.81644,0.00000,0.0,0.0,0.0,0.0,1
chr10:101156627-101190381,GOT1,0.00000,0.0,0.0,3.98603,0.00000,0.0,0.0,0.0,0.0,1
chr10:101286107-101290934,LINC01475,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0
chr10:101286705-101288224,AL513542.1,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0
chr10:101292699-101296281,NKX2-3,8.02894,0.0,0.0,13.50215,9.78393,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
chrX:9217960-9243246,AC003684.1,0.00000,0.0,0.0,4.01233,0.00000,0.0,0.0,0.0,0.0,1
chrX:9983294-10112514,WWC3,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1
chrX:99899192-99930785,SRPX2,0.00000,0.0,0.0,0.00000,4.75055,0.0,0.0,0.0,0.0,1
chrX:9992882-10006694,WWC3-AS1,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1
chrY:16634453-16957530,NLGN4Y,0.00000,0.0,0.0,5.18598,0.00000,0.0,0.0,0.0,0.0,1

In [48]:
finalDF.columns.values[-1] = 'enhancer'
finalDF

,,H3K27me3,H3K36me3,H3K4me1,H3K4me2,H3K4me3,H3K79me2,H3K9ac,H3K9me3,H4K20me1,enhancer
Pos,gene_name,,,,,,,,,,
chr10:100216834-100995619,HPSE2,0.00000,0.0,0.0,5.81644,0.00000,0.0,0.0,0.0,0.0,1
chr10:101156627-101190381,GOT1,0.00000,0.0,0.0,3.98603,0.00000,0.0,0.0,0.0,0.0,1
chr10:101286107-101290934,LINC01475,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0
chr10:101286705-101288224,AL513542.1,7.41865,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0
chr10:101292699-101296281,NKX2-3,8.02894,0.0,0.0,13.50215,9.78393,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
chrX:9217960-9243246,AC003684.1,0.00000,0.0,0.0,4.01233,0.00000,0.0,0.0,0.0,0.0,1
chrX:9983294-10112514,WWC3,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1
chrX:99899192-99930785,SRPX2,0.00000,0.0,0.0,0.00000,4.75055,0.0,0.0,0.0,0.0,1
chrX:9992882-10006694,WWC3-AS1,0.00000,0.0,0.0,4.41356,0.00000,0.0,0.0,0.0,0.0,1
chrY:16634453-16957530,NLGN4Y,0.00000,0.0,0.0,5.18598,0.00000,0.0,0.0,0.0,0.0,1

In [ ]:
finalDf.to_csv("final_data.HepG2.Histone.Enhancer.csv")